name: sync-code
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 0-16,22-23 * * *'
jobs:
  sync:
    runs-on: ubuntu-18.04
    if: github.repository == 'RikudouPatrickstar/jd_scripts'
    timeout-minutes: 2
    steps:
    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d
        sudo -E apt-get update -y
        sudo -E apt-get install -y build-essential git git-core curl wget jq
        sudo -E apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
    - name: Get Code 01
      run: |
        mkdir -p ~/.ssh
        echo -e "${{ secrets.LXKEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitee.com > ~/.ssh/known_hosts
        git clone -b master git@gitee.com:lxk0301/jd_scripts.git scripts
    # - name: Get Code 02
    #   run: |
    #     docker pull lxk0301/jd_scripts:latest
    #     docker save lxk0301/jd_scripts:latest > jd.tar
    #     tar -xvf jd.tar
    #     layer_file=$(cat manifest.json | jq ".[0]" | jq ".Layers" | jq ".[1]" | sed 's,",,g')
    #     cp $layer_file ./
    #     tar -xvf layer.tar
    # - name: Get Code 03
    #   run: |
    #     mkdir -p ~/.ssh
    #     echo -e "${{ secrets.DOVEKEY }}" > ~/.ssh/id_rsa
    #     chmod 600 ~/.ssh/id_rsa
    #     ssh-keyscan githb.com > ~/.ssh/known_hosts
    #     git clone -b master git@github.com:DoveBoy/scf.git scripts
    - name: Push to GitHub
      run: |
        echo -e "${{ secrets.GITHUBKEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com > ~/.ssh/known_hosts
        cd scripts
        git remote add github "${{ secrets.GITHUBREPO }}"
        git push -u github master >/dev/null 2>&1
    - name: Push to Gitee
      run: |
        echo -e "${{ secrets.GITEEKEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitee.com > ~/.ssh/known_hosts
        cd scripts
        git remote add gitee "${{ secrets.GITEEREPO }}"
        git push -u gitee master >/dev/null 2>&1
    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 0
